##### CONFIGURATION FILE #####

# FILE LOCATIONS
IMAGE_DIR = '/Volumes/WD4/Current/tractor_pipeline/data/external'
CATALOG_DIR = '/Volumes/WD4/Current/tractor_pipeline/data/catalogs'
INTERIM_DIR = '/Volumes/WD4/Current/tractor_pipeline/data/interim'
BRICK_DIR = '/Volumes/WD4/Current/tractor_pipeline/data/bricks'
OVERWRITE = True

DETECTION_NICKNAME = 'DETECTION'
DETECTION_FILENAME = 'mosaic_detection.EXT.fits' # fill with 'EXT'
DETECTION_ZPT = 0.00

MODELING_NICKNAME = 'MODELING'
MODELING_FILENAME = 'mosaic_hsc_i.EXT.fits' # fill with 'EXT'
MODELING_ZPT = 23.93

MULTIBAND_NICKNAME = 'MULTIBAND'
MULTIBAND_FILENAME = 'mosaic_BAND.EXT.fits' # fill with 'BAND' and 'EXT'
BANDS = ['hsc_i', 'hsc_z']
MULTIBAND_ZPT = [23.93, 23.93]

IMAGE_EXT = 'img'
WEIGHT_EXT = 'wht'
MASK_EXT = 'mask'

VERBOSE = True
VERBOSE2 = False
NTHREADS = 11
NBLOBS = 10
PLOT = False
PLOT_DIR = '/Volumes/WD4/Current/tractor_pipeline/data/figures'

# SOURCE DETECTION WITH SEXTRACTOR
DETECT_BW = 3 # increase for phot
DETECT_BH = 3
SUBTRACT_BW = 128
SUBTRACT_BH = 128
USE_FLAT = True
THRESH = 1.5 # <sigma>
MINAREA = 5 
FILTER_KERNEL = "gauss_3.0_5x5.conv"
FILTER_TYPE = 'matched'
DEBLEND_NTHRESH = 32
DEBLEND_CONT = 0.00001

# PSF MAKER
PSF_DIR = '/Volumes/WD4/Current/tractor_pipeline/data/psfmodels/vihang'
MOD_REFF_LIMITS = (4.1, 5.1)
MOD_VAL_LIMITS = (18.5, 20.5) 
MULTIBAND_REFF_LIMITS = ((2.5, 3.2), (2.3, 3.2), (2., 3.), (2., 3.), (2.1, 2.9))
MULTIBAND_VAL_LIMITS = ((21.0, 22.5), (20.0, 22.0), (20., 22.0), (19., 21.0), (19., 21.0))
PSF_SIGMA = 1.

# IMAGE PARAMETERS
PIXEL_SCALE = 0.15  # This is optional...yes?

# APERTURE PHOTOMETRY
DO_APPHOT = True
APER_PHOT = [1., 2., 3., 4., 5.]

# BUFFERS AND SEGMENT DILATION
BRICK_WIDTH = 2000
BRICK_HEIGHT = 2000
BRICK_BUFFER = 100
BLOB_BUFFER = 10
DILATION_RADIUS = 4

MOSAIC_WIDTH = 50000
MOSAIC_HEIGHT = 50000

# TRACTOR OPTIMIZATION
TRACTOR_MAXSTEPS = 150
TRACTOR_CONTHRESH = 1E-6
USE_REDUCEDCHISQ = True
PS_SG_THRESH = 0.1
EXP_DEV_THRESH = 0.5
FREEZE_POSITION = True

# RESIDUAL SOURCE DETECTION WITH SEXTRACTOR
DO_SEXPHOT = False
RES_THRESH = 5 # <sigma>
RES_MINAREA = 5
RES_DEBLEND_NTHRESH = 10
RES_DEBLEND_CONT = 0.0001

# BAD BLOB REJECTION
SPARSE_THRESH = 0.85
SPARSE_SIZE = 1000
