##### CONFIGURATION FILE #####

# SOURCE DETECTION WITH SEXTRACTOR
BW = 16
BH = 16
THRESH = 5 # <sigma>
MINAREA = 5 
DEBLEND_NTHRESH = 10
DEBLEND_CONT = 0.0001

# IMAGE PARAMETERS
PIXEL_SCALE = 0.15

# APERTURE PHOTOMETRY
APER_PHOT = [0.5, 0.75, 1., 1.5, 2., 3.5, 5., 7.]

# BUFFERS AND SEGMENT DILATION
BRICK_BUFFER = 75
BLOB_BUFFER = 10
DILATION_RADIUS = 12

# TRACTOR OPTIMIZATION
TRACTOR_MAXSTEPS = 100
TRACTOR_CONTHRESH = 1E-3
EXP_DEV_THRESH = 25

# RESIDUAL SOURCE DETECTION WITH SEXTRACTOR
RES_THRESH = 5 # <sigma>
RES_MINAREA = 5
RES_DEBLEND_NTHRESH = 10
RES_DEBLEND_CONT = 0.0001
