##### CONFIGURATION FILE #####

# SOURCE DETECTION WITH SEXTRACTOR
BW = 16
BH = 16
THRESH = 3 # <sigma>
MINAREA = 5
DEBLEND_NTHRESH = 32
DEBLEND_CONT = 0.001

# BUFFERS AND SEGMENT DILATION
BRICK_BUFFER = 75
BLOB_BUFFER = 10
DILATION_RADIUS = 12
